#!/usr/bin/env python3
"""Enhanced HTML Dashboard with Risk Trends.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
OUT_HTML = REPORTS / "dashboard.html"

def get_history() -> list:
    history = []
    for f in sorted(REPORTS.glob("risk-score-*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
            history.append({
                "date": data.get("timestamp", "").split("T")[0],
                "score": data.get("score", 0),
                "level": data.get("level", "UNKNOWN")
            })
        except: pass
    return history[-10:] # Last 10 runs

def gen_html(latest: dict, history: list) -> str:
    history_html = ""
    for h in history:
        color = "green" if h["score"] >= 80 else "orange" if h["score"] >= 60 else "red"
        history_html += f"""
        <div style="display: flex; align-items: center; margin-bottom: 5px;">
            <span style="width: 100px;">{h['date']}</span>
            <div style="background: #eee; flex-grow: 1; height: 20px; border-radius: 10px; overflow: hidden;">
                <div style="background: {color}; width: {h['score']}%; height: 100%;"></div>
            </div>
            <span style="width: 50px; text-align: right; margin-left: 10px;">{h['score']}</span>
        </div>
        """

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>OpenClaw Guardrails Dashboard</title>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 0 20px; }}
            .card {{ border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
            .score {{ font-size: 48px; font-weight: bold; text-align: center; margin: 20px 0; }}
            .level {{ text-align: center; font-size: 24px; text-transform: uppercase; letter-spacing: 2px; }}
            .green {{ color: #28a745; }} .orange {{ color: #fd7e14; }} .red {{ color: #dc3545; }}
            h2 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        </style>
    </head>
    <body>
        <h1>🛡️ OpenClaw Guardrails</h1>
        <div class="card">
            <div class="score {latest['level'].lower()}">{latest['score']}</div>
            <div class="level {latest['level'].lower()}">{latest['color']} {latest['level']} RISK</div>
            <p style="text-align: center; color: #666;">Last Updated: {latest['timestamp']}</p>
        </div>

        <h2>📈 Risk History (Last 10 Runs)</h2>
        <div class="card">
            {history_html}
        </div>

        <h2>🔍 Breakdown</h2>
        <div class="card">
            <ul>
                {"".join([f"<li><strong>{b['category']}</strong>: -{b['deduction']} pts</li>" for b in latest.get('breakdown', [])])}
            </ul>
        </div>
        
        <footer style="text-align: center; margin-top: 40px; color: #999; font-size: 12px;">
            Generated by openclaw-guardrails &bull; <a href="https://github.com/lttcnly/openclaw-guardrails" style="color: #999;">GitHub</a>
        </footer>
    </body>
    </html>
    """

def main():
    # Load meta to get latest score
    meta_file = REPORTS / "meta.json"
    if not meta_file.exists(): return
    
    meta = json.loads(meta_file.read_text())
    latest_score_path = meta.get("risk_score", {}).get("latest")
    if not latest_score_path or not Path(latest_score_path).exists(): return
    
    latest = json.loads(Path(latest_score_path).read_text())
    history = get_history()
    
    html = gen_html(latest, history)
    OUT_HTML.write_text(html, encoding="utf-8")
    print(f"Dashboard generated: {OUT_HTML}")

if __name__ == "__main__":
    main()
